### ISSUE TITLE
Add command for `sourcekitten format`

### ISSUE THREAD

**Issue by modocache** [modocache/nuclide#13]
Format your Swift source code from within Nuclide.

**Comment by nmote** [comment]
Check out the `nuclide-code-format` package. I haven't worked with it but it should be pretty easy.

**Comment by modocache** [comment]
Question: `sourcekitten format` can already format any Swift code. Does the `nuclide-code-format` package add some sort of Nuclide UI niceties on top of that...?

**Comment by nmote** [comment]
It's just the language-agnostic UI that individual language services can plug into. Probably you'll just want to write a code format provider that calls `sourcekitten format` and that will be it.

**Comment by jarsen** [comment]
Is this done? It appears all plugged in: `nuclide-code-format:format-code` is running `sourcekitten format` for me.

**Comment by modocache** [comment]
Yup, this is done. Could use some cleaning up, but I'm doing that on the `nuclide-swift-cleanup` branch. Thanks, @jarsen!
