### ISSUE TITLE
Add snippets for `for` loops and other common code blocks

### ISSUE THREAD

**Issue by modocache** [modocache/nuclide#15]
SourceKitten's autocompletion is great, but it doesn't provide suggestions for things like `for` loops. Perhaps `fo...` should expand to `for ${1:i} in ${2:0..<10} {\n    ${3:// ...}\n}`:

``` swift
for i in 0..<10 {
     // ...
}
```

**Comment by modocache** [comment]
@kastiglione is working on this.

**Comment by kastiglione** [comment]
- https://github.com/atom/snippets
- http://flight-manual.atom.io/using-atom/sections/snippets/

**Comment by kastiglione** [comment]
@modocache off the top of your head, which autocompletions are the top most priority?

**Comment by modocache** [comment]
Hmm, not sure. `for` and `if` seem like the highest priority... maybe also `guard-else`?

**Comment by kastiglione** [comment]
Note that it appears package snippets don't take affect until after restarting Atom.
