### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by modocache** [modocache/nuclide#16]
I use the `language-swift` package for Swift syntax highlighting in Atom. Thanks to the SwiftPMBuildSystem and the compile commands, we can probably do _way_ better here.

At the very least, we can use the `sourcekitten syntax` command. That command doesn't take a `--compilerargs`, but what if we modified it so that it did? Could we get even better syntax highlighting?

Without compiler args, SourceKitten reports the vast majority of symbols as `source.lang.swift.syntaxtype.identifier`, whether they're initializing a struct or calling a function. Xcode, on the other hand, is able to color structs and functions differently. If we passed better args to SourceKit, would we be able to get better type info? Or should we be using a different command, like `sourcekitten structure`?

**Comment by jarsen** [comment]
Been doing some research. Seems like dynamic grammars are possible (there appears to be a typescript package doing it), but require some hacking. Will do some more digging later, but sharing what I've found so far:
- https://discuss.atom.io/t/custom-grammar-based-on-external-tokenizer/19537
- https://github.com/atom/first-mate/issues/35

**Comment by modocache** [comment]
Haha, _of course_ @jpsim, the author of SourceKitten, was the one to ask the question of external tokenizers. 😂 

Looks like someone needs to grok the TypeScript package to move forward here. Do you think you're up to this, @jarsen? That'd free me up to focus on upstreaming, see: https://github.com/facebook/nuclide/pull/621.

**Comment by jarsen** [comment]
Sure! I've been meaning to look deeper. Hopefully this weekend I'll have a good chunk of time to dive in.

And yeah I thought it was funny it was JP asking too 😄

**Comment by modocache** [comment]
Migrated to https://github.com/facebook/nuclide/issues/649. Thanks for the awesome info, @jarsen!

**Comment by jarsen** [comment]
@modocache Yeah, sorry I wasn't more on top of this. New home owner and a bunch of stuff came up -_-. Hopefully someone with some typescript expertise can take a look 😄

**Comment by modocache** [comment]
@jarsen No worries at all! I've migrated all of the nuclide-swift issues over. If you ever have some free time to work on them, check out [the "nuclide-swift" label on facebook/nuclide](https://github.com/facebook/nuclide/labels/nuclide-swift).
