### ISSUE TITLE
Commands for `swift package`

### ISSUE THREAD

**Issue by modocache** [modocache/nuclide#3]
- Nuclide > Swift > Create new package (swift package init)
- Nuclide > Swift > Fetch current package’s dependencies (swift package fetch)
- Nuclide > Swift > Update current package’s dependencies (swift package update)
- Nuclide > Swift > Generate Xcode project for current package (swift package generate-xcodeproj)
- Nuclide > Swift > Visualize current package’s dependencies (swift package show-dependencies)
- Nuclide > Swift > Display buffer for current package’s description as JSON (swift package dump-package)

These should also be available via the command palette. Shortcut keys would be nice where appropriate.

**Comment by kacasey8** [comment]
working at this (not sure how to assign myself)

**Comment by modocache** [comment]
Yeah, weird, I have no idea how to assign it to you either.

Anyway, #10 took care of this -- thanks!
