### ISSUE TITLE
Remove implicit dependency on language-swift package

### ISSUE THREAD

**Issue by modocache** [modocache/nuclide#32]
In order for autocompletion to work, Atom needs to recognize `.swift` files as Swift files. It turns out this worked for me because I had the `language-swift` package installed. Instead of relying on the user having this package installed, `nuclide-swift` (our package) should also register `.swift` files.

I'm not exactly sure how to do this... but in order to verify, try installing `language-swift`, verifying that autocompletion works, disabling `language-swift`, then verifying that autocompletion _still_ works.

**Comment by jarsen** [comment]
Looking into it, from what I can tell it seems like handling Swift here would be most analogous to how Nuclide is handling Hack— Obj-C, JavaScript, etc., are already in atom core. To follow the existing pattern, looks like it would entail creating a `nuclide-language-swift` folder and putting the corresponding grammars and such there.

**Comment by jarsen** [comment]
Of course, this approach more _replaces_ than separates `nuclide-swift` from `language-swift`. I'm not sure if this is desired. Could give more flexibility in the future to offer better syntax highlighting?

**Comment by jarsen** [comment]
Here's the [WIP](https://github.com/jarsen/nuclide/tree/remove-language-swift-dependency) I've got going.

**Comment by modocache** [comment]
Thanks! Although, I don't think we should copy the syntax highlighting grammar from language-swift.

I was under the impression that Nuclide wouldn't register .swift files (and so won't show our autocompletion, type hints, etc.) unless we include a `grammars/swift.cson` file. Is this accurate? If so, I think the solution here is to add a nearly empty `swift.cson` file, then work on syntax highlighting in #9.

**Comment by jarsen** [comment]
That is my understanding as well. I'll remove all the rules from the grammar file.

Do you think we should put the `grammars/` in `nuclide-swift`? Or follow the pattern that Hack is doing and have a separate `nuclide-language-swift`? We already have `snippets/` in `nuclide-swift`.

**Comment by modocache** [comment]
Thanks @jarsen. Your contributions here were merged as part of https://github.com/facebook/nuclide/commit/89293ac03106999220651ebbb85fe6a42820e2f5. Thanks!!
