### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by botero-dev** [modocache/nuclide#37]
Is there linux support? I couldn't find mention of it.
I guess it is because of the sourcekitten dependency, which depends on sourcekit and it depends on libdispatch, so it could take a while to have sourcekitten support.

There is `swift-ide-test` for linux but I don't know if it would be useful or possible at all

**Comment by modocache** [comment]
I estimate SourceKit will be available on Linux within several weeks, and SourceKitten is already working on Linux support: https://github.com/jpsim/SourceKitten/pull/223

For now, I'm afraid Nuclide only supports autocompletion and other features on macOS, not Linux.

**Comment by botero-dev** [comment]
Nice =D I didn't know that. I thought SourceKitten was planned for much later but its good to know that it is in the works now.

**Comment by zxw454034941** [comment]
SourceKitten can build on linux now:jpsim/SourceKitten#223.
I set the path for the SourceKitten Executable in nuclide setting, but the autocompletion didn't work.
Is there any other works to do to support on linux?

**Comment by modocache** [comment]
@zxw454034941 Did you try using an official Nuclide release?

I don't remember, but I imagine there are still one or two minor things to do to support Linux.

I'll migrate this issue to facebook/nuclide, since all development is being done on the official repository now.

**Comment by zxw454034941** [comment]
@modocache Thank you for your reply,  I just used the official Nuclide release.

Hope to fix the linux support. 

Another small question,  will Nuclide support swift debugger?

**Comment by modocache** [comment]
@zxw454034941 Did you build your Swift package via the Nuclide toolbar? You need to build once before any autocompletion results appear.

**Comment by modocache** [comment]
I'm migrating this issue to https://github.com/facebook/nuclide/issues/678. Thanks all!

@zxw454034941 What kind of Swift debugger support would you like to see?

**Comment by zxw454034941** [comment]
@modocache just like you mentioned: modocache/nuclide#28

**Comment by modocache** [comment]
Ah, gotcha. I didn't move that issue to the facebook/nuclide repository because I think it might already work. Have you tried attaching a debugger via Nuclide to a SwiftPM-built executable built in Debug mode? I think it may work right now.
